name: Swift Experimental Debug Build

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode-15.0.1.app/Contents/Developer
  DEPLOYMENT_LOCAL_SUBDIR: swift-experimental-debug
  DEPLOYMENT_ZIP: swift-experimental-debug.zip
  BUILT_SWIFT_SUBDIR: build/Ninja-ReleaseAssert+swift-DebugAssert/swift-macosx-x86_64/bin
  DEPLOY_TO_SERVER: false

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clean
      run: rm -rf *

    - uses: actions/checkout@v3
      with:
        path: swift

    - name: Checkout related projects and configure
      run: |
        swift/checkout-swift-ci.sh debug

    - name: Build
      run: |
        swift/build-swift-ci.sh debug

    - name: Stage
      # if: ${{ github.event_name == 'push' }}
      run: |
        rm -rf ${HOME}/built/${DEPLOYMENT_LOCAL_SUBDIR} ${HOME}/built/${DEPLOYMENT_ZIP}
        mkdir -p ${HOME}/built/${DEPLOYMENT_LOCAL_SUBDIR}
        cp -fa ${BUILT_SWIFT_SUBDIR}/{swift,swift-ide-test,swiftc,swift-frontend} ${HOME}/built/${DEPLOYMENT_LOCAL_SUBDIR}/
        cd ${HOME}/built
        zip --symlinks -r ${DEPLOYMENT_ZIP} ${DEPLOYMENT_LOCAL_SUBDIR}/

    # - name: Deploy
    #   if: ${{ github.event_name == 'push' }}
    #   run: scp -P 227 ${HOME}/built/${DEPLOYMENT_ZIP} ubuntu@swiftforarduino.com:web-s4a-private/compilers/
          
