name: Swift 5.9

on:
  workflow_dispatch:
  push:
    branches: [ "avr-support-12" ]
  pull_request:
    branches: [ "avr-support-12" ]

env:
  CI_SERVER: 1
  DEVELOPER_DIR: "/Applications/Xcode-13.2.1.app/Contents/Developer"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clean
      run: rm -rf *

    - uses: actions/checkout@v3
      with:
        path: swift

    - name: Checkout related projects and configure
      run: |
        swift/checkout-swift-ci.sh

    - name: Build
      run: |
        swift/build-swift-ci.sh

    - name: Stage
      if: ${{ github.event_name == 'push' }}
      run: |
        cp -fa build/Ninja-ReleaseAssert/swift-macosx-x86_64/bin/{swift,swift-ide-test,swiftc,swift-frontend} ${HOME}/built/swift-5.9/
        cd ${HOME}/built
        zip --symlinks  -r swift-5.9.zip swift-5.9/

    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      run: scp -P 227 ${HOME}/built/swift-5.9.zip carl@swiftforarduino.com:web-s4a-private/compilers/
