name: Swift Debug

on:
  workflow_dispatch:
  push:
    branches: [ "avr-support-8" ]
  pull_request:
    branches: [ "avr-support-8" ]

env:
  CI_SERVER: 1
  DEVELOPER_DIR: "/Applications/Xcode.app/Contents/Developer"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Supporting Files And Configure
      run: |
        cd ..
        swift/checkout-swift-ci.sh debug

    - name: Build
      run: |
        cd ..
        swift/build-swift-ci.sh debug
