name: Swift

on:
  workflow_dispatch:
  push:
    branches: [ "avr-support-8" ]
  pull_request:
    branches: [ "avr-support-8" ]

env:
  CI_SERVER: 1
  DEVELOPER_DIR: "/Applications/Xcode.app/Contents/Developer"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Supporting Files And Configure
      run: |
        ./checkout-swift-ci.sh

    - name: Build
      run: |
        ./build-swift-ci.sh         
